package org.xena.cs

import org.xena.offsets.OffsetManager.process

/**
 * Created by Jonathan on 7/12/2016.
 */
enum class EntityType(val classId: Int, val weapon: Boolean = false, val grenade: Boolean = false) {
	
	NextBotCombatCharacter(0),
	CWeaponCubemap(0),
	CPropVehicleChoreoGeneric(0),
	CItemAssaultSuitUseable(0),
	CItem(0),
	CAI_BaseNPC(0),
	CAK47(1, weapon = true),
	CBaseAnimating(2),
	CBaseAnimatingOverlay(3),
	CBaseAttributableItem(4),
	CBaseButton(5),
	CBaseCombatCharacter(6),
	CBaseCombatWeapon(7),
	CBaseCSGrenade(8, grenade = true),
	CBaseCSGrenadeProjectile(9, grenade = true),
	CBaseDoor(10),
	CBaseEntity(11),
	CBaseFlex(12),
	CBaseGrenade(13, grenade = true),
	CBaseParticleEntity(14),
	CBasePlayer(15),
	CBasePropDoor(16),
	CBaseTeamObjectiveResource(17),
	CBaseTempEntity(18),
	CBaseToggle(19),
	CBaseTrigger(20),
	CBaseViewModel(21),
	CBaseVPhysicsTrigger(22),
	CBaseWeaponWorldModel(23),
	CBeam(24),
	CBeamSpotlight(25),
	CBoneFollower(26),
	CBreakableProp(27),
	CBreakableSurface(28),
	CC4(29),
	CCascadeLight(30),
	CChicken(31),
	CColorCorrection(32),
	CColorCorrectionVolume(33),
	CCSGameRulesProxy(34),
	CCSPlayer(35),
	CCSPlayerResource(36),
	CCSRagdoll(37),
	CCSTeam(38),
	CDEagle(39, weapon = true),
	CDecoyGrenade(40, grenade = true),
	CDecoyProjectile(41, grenade = true),
	CDynamicLight(42),
	CDynamicProp(43),
	CEconEntity(44),
	CEconWearable(45),
	CEmbers(46),
	CEntityDissolve(47),
	CEntityFlame(48),
	CEntityFreezing(49),
	CEntityParticleTrail(50),
	CEnvAmbientLight(51),
	CEnvDetailController(52),
	CEnvDOFController(53),
	CEnvParticleScript(54),
	CEnvProjectedTexture(55),
	CEnvQuadraticBeam(56),
	CEnvScreenEffect(57),
	CEnvScreenOverlay(58),
	CEnvTonemapController(59),
	CEnvWind(60),
	CFEPlayerDecal(61),
	CFireCrackerBlast(62),
	CFireSmoke(63),
	CFireTrail(64, grenade = true),
	CFish(65),
	CFlashbang(66, grenade = true),
	CFogController(67),
	CFootstepControl(68),
	CFunc_Dust(69),
	CFunc_LOD(70),
	CFuncAreaPortalWindow(71),
	CFuncBrush(72),
	CFuncConveyor(73),
	CFuncLadder(74),
	CFuncMonitor(75),
	CFuncMoveLinear(76),
	CFuncOccluder(77),
	CFuncReflectiveGlass(78),
	CFuncRotating(79),
	CFuncSmokeVolume(80),
	CFuncTrackTrain(81),
	CGameRulesProxy(82),
	CHandleTest(83),
	CHEGrenade(84, grenade = true),
	CHostage(85),
	CHostageCarriableProp(86),
	CIncendiaryGrenade(87, grenade = true),
	CInferno(88, grenade = true),
	CInfoLadderDismount(89),
	CInfoOverlayAccessor(90),
	CItem_Healthshot(91),
	CItemDogtags(92),
	CKnife(93, weapon = true),
	CKnifeGG(94, weapon = true),
	CLightGlow(95),
	CMaterialModifyControl(96),
	CMolotovGrenade(97, grenade = true),
	CMolotovProjectile(98, grenade = true),
	CMovieDisplay(99),
	CParticleFire(100),
	CParticlePerformanceMonitor(101),
	CParticleSystem(102),
	CPhysBox(103),
	CPhysBoxMultiplayer(104),
	CPhysicsProp(105),
	CPhysicsPropMultiplayer(106),
	CPhysMagnet(107),
	CPlantedC4(108),
	CPlasma(109),
	CPlayerResource(110),
	CPointCamera(111),
	CPointCommentaryNode(112),
	CPointWorldText(113),
	CPoseController(114),
	CPostProcessController(115),
	CPrecipitation(116),
	CPrecipitationBlocker(117),
	CPredictedViewModel(118),
	CProp_Hallucination(119),
	CPropDoorRotating(120),
	CPropJeep(121),
	CPropVehicleDriveable(122),
	CRagdollManager(123),
	CRagdollProp(124),
	CRagdollPropAttached(125),
	CRopeKeyframe(126),
	CSCAR17(127, weapon = true),
	CSceneEntity(128),
	CSensorGrenade(129),
	CSensorGrenadeProjectile(130),
	CShadowControl(131),
	CSlideshowDisplay(132),
	CSmokeGrenade(133, grenade = true),
	CSmokeGrenadeProjectile(134, grenade = true),
	CSmokeStack(135),
	CSpatialEntity(136),
	CSpotlightEnd(137),
	CSprite(138),
	CSpriteOriented(139),
	CSpriteTrail(140),
	CStatueProp(141),
	CSteamJet(142),
	CSun(143),
	CSunlightShadowControl(144),
	CTeam(145),
	CTeamplayRoundBasedRulesProxy(146),
	CTEArmorRicochet(147),
	CTEBaseBeam(148),
	CTEBeamEntPoint(149),
	CTEBeamEnts(150),
	CTEBeamFollow(151),
	CTEBeamLaser(152),
	CTEBeamPoints(153),
	CTEBeamRing(154),
	CTEBeamRingPoint(155),
	CTEBeamSpline(156),
	CTEBloodSprite(157),
	CTEBloodStream(158),
	CTEBreakModel(159),
	CTEBSPDecal(160),
	CTEBubbles(161),
	CTEBubbleTrail(162),
	CTEClientProjectile(163),
	CTEDecal(164),
	CTEDust(165),
	CTEDynamicLight(166),
	CTEEffectDispatch(167),
	CTEEnergySplash(168),
	CTEExplosion(169),
	CTEFireBullets(170),
	CTEFizz(171),
	CTEFootprintDecal(172),
	CTEFoundryHelpers(173),
	CTEGaussExplosion(174),
	CTEGlowSprite(175),
	CTEImpact(176),
	CTEKillPlayerAttachments(177),
	CTELargeFunnel(178),
	CTEMetalSparks(179),
	CTEMuzzleFlash(180),
	CTEParticleSystem(181),
	CTEPhysicsProp(182),
	CTEPlantBomb(183),
	CTEPlayerAnimEvent(184),
	CTEPlayerDecal(185),
	CTEProjectedDecal(186),
	CTERadioIcon(187),
	CTEShatterSurface(188),
	CTEShowLine(189),
	CTesla(190),
	CTESmoke(191),
	CTESparks(192),
	CTESprite(193),
	CTESpriteSpray(194),
	CTest_ProxyToggle_Networkable(195),
	CTestTraceline(196),
	CTEWorldDecal(197),
	CTriggerPlayerMovement(198),
	CTriggerSoundOperator(199),
	CVGuiScreen(200),
	CVoteController(201),
	CWaterBullet(202),
	CWaterLODControl(203),
	CWeaponAug(204, weapon = true),
	CWeaponAWP(205, weapon = true),
	CWeaponBaseItem(206),
	CWeaponBizon(207, weapon = true),
	CWeaponCSBase(208, weapon = true),
	CWeaponCSBaseGun(209, weapon = true),
	CWeaponCycler(210, weapon = true),
	CWeaponElite(211, weapon = true),
	CWeaponFamas(212, weapon = true),
	CWeaponFiveSeven(213, weapon = true),
	CWeaponG3SG1(214, weapon = true),
	CWeaponGalil(215, weapon = true),
	CWeaponGalilAR(216, weapon = true),
	CWeaponGlock(217, weapon = true),
	CWeaponHKP2000(218, weapon = true),
	CWeaponM249(219, weapon = true),
	CWeaponM3(220, weapon = true),
	CWeaponM4A1(221, weapon = true),
	CWeaponMAC10(222, weapon = true),
	CWeaponMag7(223, weapon = true),
	CWeaponMP5Navy(224, weapon = true),
	CWeaponMP7(225, weapon = true),
	CWeaponMP9(226, weapon = true),
	CWeaponNegev(227, weapon = true),
	CWeaponNOVA(228, weapon = true),
	CWeaponP228(229, weapon = true),
	CWeaponP250(230, weapon = true),
	CWeaponP90(231, weapon = true),
	CWeaponSawedoff(232, weapon = true),
	CWeaponSCAR20(233, weapon = true),
	CWeaponScout(234, weapon = true),
	CWeaponSG550(235, weapon = true),
	CWeaponSG552(236, weapon = true),
	CWeaponSG556(237, weapon = true),
	CWeaponSSG08(238, weapon = true),
	CWeaponTaser(239, weapon = true),
	CWeaponTec9(240, weapon = true),
	CWeaponTMP(241, weapon = true),
	CWeaponUMP45(242, weapon = true),
	CWeaponUSP(243, weapon = true),
	CWeaponXM1014(244, weapon = true),
	CWorld(245),
	CWorldVguiText(246),
	DustTrail(247),
	MovieExplosion(248),
	ParticleSmokeGrenade(249, grenade = true),
	RocketTrail(250),
	SmokeTrail(251, grenade = true),
	SporeExplosion(252),
	SporeTrail(253);
	
	companion object {
		
		@JvmStatic
		private val cachedValues = values()
		
		@JvmStatic
		fun byId(id: Int) = cachedValues.firstOrNull { it.classId == id }
		
		@JvmStatic
		fun byAddress(address: Long): EntityType? {
			try {
				val vt = process().readUnsignedInt(address + 0x8)
				if (vt <= 0) {
					return null
				}
				val fn = process().readUnsignedInt(vt + 0x8)
				if (fn <= 0) {
					return null
				}
				val cls = process().readUnsignedInt(fn + 0x1)
				if (cls <= 0) {
					return null
				}
				val classId = process().readUnsignedInt(cls + 20).toInt()
				return EntityType.byId(classId)
			} catch (e: Exception) {
				//e.printStackTrace()
				return null
			}
		}
		
	}
	
}